development:
  access_key_id: 0TB087HMYBZ4DW2A1WG2
  secret_access_key: j+FSrP3d7vTi6KTJkciOXHTb1+Dk3feF4YKyhgrX
test:
  access_key_id: abc...
  secret_access_key: abc...
production:
  access_key_id: 0TB087HMYBZ4DW2A1WG2
  secret_access_key: j+FSrP3d7vTi6KTJkciOXHTb1+Dk3feF4YKyhgrX
staging:
  access_key_id: 0TB087HMYBZ4DW2A1WG2
  secret_access_key: j+FSrP3d7vTi6KTJkciOXHTb1+Dk3feF4YKyhgrX